module aeondds 
{
  module arinterface
  {
    // Topic names
    const string TOPIC_AR_NAVDATA_DEMO 		= "NavdataDemo";
    const string TOPIC_AR_NAVDATA_TIME 		= "NavdataTime";
    const string TOPIC_AR_NAVDATA_RAW_MEASURES 	= "NavdataRawMeasures";
    const string TOPIC_AR_NAVDATA_PWM 		= "NavdataPwm";
    const string TOPIC_AR_NAVDATA_ALTITUDE 	= "NavdataAltitude";
    const string TOPIC_AR_NAVDATA_PRESSURE_RAW 	= "NavdataPressureRaw";
    const string TOPIC_AR_NAVDATA_MAGNETO 	= "NavdataMagneto";
    const string TOPIC_AR_NAVDATA_WIFI 		= "NavdataWifi";
    
    struct TVec3f
    {
      float x;
      float y;
      float z;
    };
    
    struct TNavdataDemo
    {
      unsigned long controlState;
      unsigned long batteryPercentage;
      
      float theta;
      float phi;
      float psi;
      
      long altitude;
      
      float vx;
      float vy;
      float vz;
    };
    
    struct TNavdataTime
    {
      unsigned long timestamp;
    };
    
    struct TNavdataRawMeasures
    { 
      sequence<unsigned short,3> rawAccelerometer;
      sequence<short,3> rawGyros;
      sequence<short,2> rawGyros_xy110;
      unsigned long rawBatteryVoltage;
    };
    
    struct TNavdataPwm
    {
      octet motor1;
      octet motor2;
      octet motor3;
      octet motor4;
      octet satMotor1;
      octet satMotor2;
      octet satMotor3;
      octet satMotor4;
      unsigned short currentMotor1;
      unsigned short currentMotor2;
      unsigned short currentMotor3;
      unsigned short currentMotor4;
    };
    
    struct TNavdataAltitude
    {
      long altitudeVision;
      float altitudeVz;
      long altitudeRef;
      long altitudeRaw;
    };
    
    struct TNavdataPressureRaw
    {
      unsigned long uP;
      unsigned short uT;
      unsigned long temperatureMeas;
      unsigned long pressureMeas;
    };
    
    struct TNavdataMagneto
    {
      short mx;
      short my;
      short mz;
      
      TVec3f raw;
      TVec3f rectified;
      TVec3f offset;
    };
    
    struct TNavdataWifi
    {
      unsigned long linkQuality;
    };

  };
};