module aeondds 
{	
	module quicklooks 
	{
	
		// Topic names
		const string TOPIC_QUICKLOOKS_VEHICLE_STREAM	= "VehicleDataStream";	// Data coming in from the vehicle in real time
		const string TOPIC_QUICKLOOKS_VIEWER_STREAM	= "ViewerDataStream";	// Data being streamed to viewers in real time
		
		struct TSensorReport
		{
		    double start_utc;
		    double stop_utc;
		    double mid_utc;
		    double longitude;
		    double latitude;
		    double pressure;
		    double altitude;
		    double temperature;
		    double relHumidity;
		    double o3_ppbv;
		    double co_ppbv;
		    double so2_ppbv;
		    double no2_ppbv;
		    double bscat450;
		    double bscat550;
		    double bscat700;
		    double bkscat450;
		    double bkscat550;
		    double bkscat700;
		    double pCounts;
		    double nDp03_0_4;
		    double nDp04_0_491;
		    double nDp0491_0_6;
		    double nDp06_0_7;
		    double dDp0700_0_8;
		    double dDp08_plus;
		    double BC_370;
		    double BC_470;
		    double BC_520;
		    double BC_590;
		    double BC_660;
		    double BC_880;
		    double BC_950;
		    double flight;
		    double spiral;
		    double raw_temperature;
		    double raw_relHumidity;
		    double raw_bscat450;
		    double raw_bscat550;
		    double raw_bscat700;
		    double raw_bkscat450;
		    double raw_bkscat550;
		    double raw_bkscat700;
		};
		
		struct TDiscoverAQReport
		{
			long vehicleId;	//@key
			long timestamp;
			double longitude;
			double latitude;
			double altitude;
			
			TSensorReport data;
			
		};
	};
};