module aeondds 
{
  module sensors
  {
    const short OBJECT_ID_LENGTH = 32;
  
    const string TOPIC_VICON_TRACK	= "ViconTrack";
  
    enum EObjectType 
    {
      VEHICLE,
      OBSTACLE
    };
  
    struct TViconTrack
    {
      string<OBJECT_ID_LENGTH>	objectId; 	//@key
      EObjectType 		objectType;
      unsigned long long	timestampMs;			

      double x_m;
      double y_m;
      double z_m;
      
      double phi_rad;	// Roll
      double theta_rad;	// Pitch
      double psi_rad;	// Yaw
      
      // Quaternion representation of attitude
      double q0;
      double q1;
      double q2;
      double q3;
    };
  };
};
