module aeondds 
{
  module video
  {
	const long MAX_FRAME_SIZE = 1048576;
  
	const long SMALL_INFRARED_STEAM_SIZE = 480;

	struct TSmallInfraredStream
	{
		long streamId; //@key

		unsigned long flags;
		unsigned long sequenceNumber;

		sequence<octet, SMALL_INFRARED_STEAM_SIZE> frame;
	};
	
	struct TGenericVideoFrame
	{
		long streamId; //@key
		
		sequence<octet, MAX_FRAME_SIZE> frame;
	};
  };
  
  
};
