// Data Definition for Communication between Master and Slave

module slave
{
	module hands 
	{
		// Topics
		const string TOPIC_SLAVE_TO_MASTER_MOBILITY_FEEDBACK = "SlaveToMasterMobilityFeedback";
		
		const long MAX_OCTETS_JSON_FILE = 10485760;		// 10MB
		
		struct TSlaveToMasterMobilityFeedback
		{
			//Voltage
			double voltage;
			//Capacitance
			double capacitance;
		};
	};
};
